# Local overrides that should survive generated theme updates

# Visual overrides
font_family JetBrains Mono Nerd Font
font_size 11.0
window_margin_width 21.75

# Edit behavior
map ctrl+backspace send_text normal,application \x17

# Tab bar
# tab_bar_edge bottom
# tab_bar_margin_height 5.0 0.0
# tab_bar_style custom
# tab_powerline_style round
# tab_title_template "{fmt.fg.default}{index}"

shell /usr/bin/fish


# Tab bar: round tabs without custom colors
tab_bar_style powerline
tab_powerline_style round
